### ISSUE TITLE
Create multiple groups each with different dashboards?

### ISSUE THREAD

**Issue by tedfeyler** [Dynatrace-Reinhard-Pilz/Dynatrace-MoM#2]
Hey Reini,

I would like to create the following:

| User Group | Dashboard | Permission | Auto Open |
| --- | --- | --- | --- |
| Developers | Triage Dashboard | Read_Write | Yes |
| Operations | Monitoring Dashboard | Read | Yes |

**I would like each user group to only have access to the DB named above (i.e., Operations should not have access to the Triage DB).**

When I run the following command:

`java -Dconfig.server.host=localhost:8021 -Dconfig.server.user=admin -Dconfig.server.pass=admin -Dvariable.environment=%env% -Dvariable.application=%app% -Dvariable.tier=CustomerFrontEnd -Dconfig.templates.profile="{@application} {@environment}" -Dconfig.user.groups.dev.name=Developers -Dconfig.user.groups.dev.management.role=Guest -Dconfig.user.groups.dev.profile.role=Administrator -Dconfig.dashboards.triage.name="{@environment}_{@application}_TRIAGE_DASHBOARD" -Dconfig.user.groups.dev.dashboards.triage.permission=Read_Write -Dconfig.user.groups.ops.name=Operations -Dconfig.user.groups.ops.management.role=Guest -Dconfig.user.groups.ops.profile.role=Guest -Dconfig.dashboards.monitoring.name="{@environment}_{@application}_JBoss Monitoring" -Dconfig.user.groups.ops.dashboards.monitoring.permission=Read -jar dt-onboarding.jar`

I end up with both User Groups having access to both Dashboards and both Dashboards are set to auto open.  Is my command syntax incorrect or is this not currently possible?

Also, is there a way to assign read/read_write access to <default> dashboard?

thanks,
ted

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Hi Ted,

Until you've opened your issue there was no way to deny access to the Dashboards to the configured user groups.

I've now checked in a version that's able to allow for that.

Your command line would then be:

`java -Dconfig.server.host=localhost:8021 -Dconfig.server.user=admin -Dconfig.server.pass=admin -Dvariable.environment=%env% -Dvariable.application=%app% -Dvariable.tier=CustomerFrontEnd -Dconfig.templates.profile="{@application} {@environment}" -Dconfig.user.groups.dev.name=Developers -Dconfig.user.groups.dev.management.role=Guest -Dconfig.user.groups.dev.profile.role=Administrator -Dconfig.dashboards.triage.name="{@environment}_{@application}_TRIAGE_DASHBOARD" -Dconfig.user.groups.dev.dashboards.triage.permission=Read_Write -Dconfig.user.groups.ops.dashboards.triage.permission=None -Dconfig.user.groups.ops.name=Operations -Dconfig.user.groups.ops.management.role=Guest -Dconfig.user.groups.ops.profile.role=Guest -Dconfig.dashboards.monitoring.name="{@environment}_{@application}_JBoss Monitoring" -Dconfig.user.groups.dev.dashboards.monitoring.permission=None -Dconfig.user.groups.ops.dashboards.monitoring.permission=Read -jar dt-onboarding.jar`

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Ted, please reopen another issue in case the solution is not what you were looking for.

**Comment by tedfeyler** [comment]
Hey Reini,

Just letting you know that I've tested it and it appears to be working designed.  Thanks!

===ted
